post_install()
{
/bin/cat <<EOT


----------------------------------------------------------------------
The Module mod_lookup_identity has been installed in:
   
   /usr/lib/httpd/modules
   
To Start using the module, add the following line to /etc/httpd/conf/httpd.conf:

LoadModule lookup_identity_module /usr/lib/httpd/modules/mod_lookup_identity.so

----------------------------------------------------------------------


EOT
}

